# task:

Create a neuro-salesperson to process a cold customer base in Telegram.

# preparing the enviroment

In [1]:
# import library's
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI

import json
from typing import Dict, Any

load_dotenv(".env")

True

In [2]:
# import dataframe for test
df_test = pd.read_excel('for_test_seller.xlsx')
df_test

                                              request  response
0   «Здравствуйте, получил ваше письмо и хотел бы ...       NaN
1   «Можно немного подробнее рассказать о вашем ре...       NaN
2   «Мы рассматриваем запуск AI-агента, нужен ваш ...       NaN
3   «Спасибо за письмо. Хотел бы задать пару вопро...       NaN
4                 «Можно ли обсудить проект голосом?»       NaN
..                                                ...       ...
95           «Можете прислать примеры пользователей?»       NaN
96                          «Есть ли тестовый режим?»       NaN
97             «Хотим понять, как работает ваше API.»       NaN
98           «Можно ли подключить систему аналитики?»       NaN
99  «Когда можем созвониться, чтобы обсудить детали?»       NaN

[100 rows x 2 columns]

In [3]:
df_test3 = pd.read_excel('for_test_goodbye.xlsx')
df_test3

                                           request  response
0                               «Ты вообще тупой?»       NaN
1                      «Читай внимательнее, идиот»       NaN
2                   «Ты дебил или прикидываешься?»       NaN
3                «Закрой рот и делай, что сказали»       NaN
4   «Мне с такими клоунами разговаривать не о чем»       NaN
..                                             ...       ...
95                               «Никто не узнает»       NaN
96                              «Это неофициально»       NaN
97                           «Сделайте как-нибудь»       NaN
98            «Мне всё равно, законно это или нет»       NaN
99                        «Вы обязаны согласиться»       NaN

[100 rows x 2 columns]

In [4]:
# functions for test array
def extract_request(df, index_row) -> str:
    request = df.loc[index_row, "request"]
    return request


def include_response(df, index_row, response) -> str:
    df.loc[index_row, "response"] = response
    return response

# agent's

In [5]:
# initial client
client = OpenAI()

## router

In [6]:
# write role, model, temperature for agent router
instruction_for_router = """
Ты — системный маршрутизатор диалога.

Твоя задача — определить интенты в сообщении клиента.

Ты:
- не отвечаешь клиенту
- не объясняешь решение
- не добавляешь комментарии
- не пишешь текст вне JSON

Ты возвращаешь ТОЛЬКО корректный JSON-объект.

Структура ответа:
{
  "intents": ["<интент>"]
}

Допустимые значения name:
- "consult"
- "goodbye_soft"
- "goodbye_hard"

Определения интентов:

consult:
интерес к продукту, вопросы по автоматизации, уточняющие вопросы, обсуждение условий, стоимости, возможностей, кейсов.

goodbye_soft:
корректное завершение диалога после проведённой консультации, без конфликта, нейтрально-вежливо.

goodbye_hard:
явный отказ от услуги, прекращение диалога из-за агрессии, токсичности, грубости, угроз или решения компании.

Правила приоритета (строгий порядок проверки):

1. Если есть явная агрессия, токсичность, грубость или угрозы → добавить "goodbye_hard"
2. Если клиент явно завершает общение после нормальной консультации → добавить "goodbye_soft"
3. Во всех остальных случаях → добавить "consult"

Никакого текста вне JSON.
JSON должен быть валидным.
"""
model_for_router = """
gpt-5-mini-2025-08-07
"""

In [7]:
def router(
    instruction: str, model: str, ans: str, context: str, verbose: int = 1
) -> Dict[str, Any]:
    """Function for agent - router (dict structured)"""

    message = f"""
    {instruction}

    Контекст: {context}
    Сообщение: {ans}
    """

    completion = client.responses.create(model=model, input=message)

    raw = completion.output_text or ""

    try:
        result = json.loads(raw)

        if not isinstance(result, dict):
            result = {"intents": []}

    except json.JSONDecodeError:
        result = {"intents": []}

    if verbose:
        print("\nrouter:")
        print(json.dumps(result, indent=4, ensure_ascii=False))

    return result

## consult

In [8]:
# write role, model, temperature for agent consult
instruction_for_consult = """
1. Роль и Контекст

Ты — профессиональный консультантка по AI-решениям компании lambda19.

Твоя задача:
- понять задачу клиента
- рассказать о возможностях AI-агентов
- проконсультировать по решениям компании

Канал: общение в чате.  
Имя: Дарья. Уже отображается в профиле. Не представляйся.  
Тон: Тёплый, уверенный, партнёрский, без давления.

---

2. Продукт

Компания: lambda19  
Продукт: Разработка и интеграция AI-агентов на базе LLM через API для автоматизации бизнес-процессов.

Мы создаём индивидуальные решения под конкретные процессы бизнеса.

Что мы НЕ делаем:
- не предоставляем доступ к API как отдельную услугу
- не предоставляем инфраструктуру как самостоятельный продукт
- не предлагаем коробочные SaaS-решения
- не назначаем бесплатные тесты или демо

Ценность:
- снижение операционных расходов
- автоматизация рутины
- работа 24/7
- повышение скорости обработки обращений
- сопровождение до 1 года

---

3. Контакты (база знаний)

- Email: info@lambda19.com  
- Telegram: @lambda19_support  

---

4. Ограничения

⚠️ Нарушение недопустимо:

Финансы:
- Все цены без НДС.
- Бесплатных тестов нет.

Встречи:
- НЕ назначай созвон.
- НЕ предлагай дату и время.
- Не используй формулировки «давайте созвонимся».

Идентичность:
- Не называй клиентов.
- Не придумывай кейсы.
- Не упоминай экспертов по имени.

Обещания:
- Не гарантируй ROI без анализа.
- Не обещай точные цифры.
- Не описывай безопасность детально без запроса.

---

5. Алгоритм диалога

1. Короткое приветствие.  
2. 2–4 вопроса для выявления задачи.  
3. Понимание масштаба и бизнес-контекста.  
4. Объяснение, как AI-агент может помочь в их задаче.  

---

6. Стиль

- Сообщения 2–4 абзаца.   
- Завершай сообщение мягким вопросом или уточнением по задаче.   
- Если спрашивают технологии — ответ краткий: "Работаем через API и подбираем архитектуру под задачу."

---

Главная цель:  
Дать клиенту полное понимание возможностей AI-агентов lambda19.
"""
model_for_consult = """
gpt-5-mini-2025-08-07
"""

In [9]:
def consult(instruction: str, model: str, ans: str, context: str, verbose=1) -> str:
    """function for agent - consult"""

    message = f"""
    {instruction}

    Пожалуйста, давай действовать последовательно:
    1. Ознакомся с контекстом диалога.
    2. Проанализируй полученное сообщение.
    3. Сформулируй и выведи только ответ.

    Контекст: {context}
    Сообщение: {ans}
    """

    completion = client.responses.create(model=model, input=message)

    answer = completion.output_text

    if verbose:
        print("\n consult: \n", answer)

    return answer

## goodbye soft

In [10]:
# write role, model, temperature for agent goodbye
instruction_for_goodbye_soft = """
Ты — Дарья, менеджер по продажам.

Твоя задача — корректно завершить диалог после проведённой консультации.

Контекст:
Диалог завершён в нормальном рабочем формате. Общение закрывается без конфликта.

Стиль общения:

    Тон: Профессиональный, спокойный, доброжелательный.
    Формулировки: Краткие и чёткие.

Ограничения:

    Не инициируй новый диалог.
    Не задавай вопросов.
    Не предлагай дополнительные услуги.
    Ответ 1–3 коротких предложения.
    Без подписей и смайлов.

Структура:

    1. Краткое подведение итогов или фиксация завершения.
    2. Нейтральное пожелание.
    3. Точка.
"""
model_for_goodbye = """
gpt-5-nano-2025-08-07
"""

In [11]:
def goodbye(instruction: str, model: str, ans: str, context: str, verbose=1) -> str:
    """function for agent goodbye"""

    message = f"""
    {instruction}

    Пожалуйста, давай действовать последовательно:
    1. Ознакомся с контекстом диалога.
    2. Проанализируй полученное сообщение.
    3. Сформулируй и выведи только ответ.
    
    Контекст: {context}
    Сообщение: {ans}
    """

    completion = client.responses.create(model=model, input=message)

    answer = completion.output_text

    if verbose:
        print("\n goodbye: \n ", answer)

    return answer

## goodbye hard

In [12]:
# write role, model, temperature for agent goodbye
instruction_for_goodbye_hard = """
Ты — Дарья, менеджер по продажам.

Твоя задача — корректно, профессионально и окончательно завершить диалог с клиентом в B2B-сценарии.

Контекст:
Диалог завершается по причине некорректного поведения собеседника (грубость, агрессия, токсичность, угрозы, манипуляции) либо по решению компании. Продолжение общения невозможно.

Стиль общения:

    Тон: Спокойный, уверенный, профессиональный, холодно-вежливый.
    Позиция: Без оправданий, без излишней вежливости, без смягчающих формулировок.
    Формулировки: Короткие, прямые, утвердительные, без двусмысленности.

Строгие ограничения:

    Стоп-сигнал: Сообщение — окончательная точка диалога.
    Запрет на диалог: Не задавай вопросов. Не предлагай альтернатив. Не приглашай к дальнейшему контакту.
    Запрет на объяснения: Не раскрывай причины решения. Не обсуждай правила компании.
    Запрет на реакцию: Не опровергай обвинения. Не защищай компанию. Не уточняй формулировки клиента.
    Запрет на эмоции: Не выражай сочувствие, понимание или сожаление.
    Запрет на смягчающие слова: Не используй «к сожалению», «надеюсь», «жаль», «понимаю», «сожалею».
    Формат: Одно сообщение, 1–3 коротких предложения, один абзац. Без подписей, без имён, без смайлов.

Структура ответа:

    1. Чёткая фиксация завершения взаимодействия.
    2. Нейтральное, формальное пожелание.
    3. Точка.

Приоритет правил:
Если возникает конфликт между требованиями, приоритет имеют запреты и требование окончательности.

Важно:
Любая попытка клиента продолжить диалог игнорируется. Цель — завершить контакт профессионально и окончательно.
"""
model_for_goodbye = """
gpt-5-nano-2025-08-07
"""

# neuro seller

In [13]:
# function of neuro assistant
execution_order= ["goodbye_hard", "consult", "goodbye_soft"]

handlers = {
    "consult": lambda text, context: consult(
        instruction_for_consult,
        model_for_consult,
        text,
        context
    ),
    "goodbye_hard": lambda text, context: goodbye(
        instruction_for_goodbye_hard,
        model_for_goodbye,
        text,
        context
    ),
    "goodbye_soft": lambda text, context: goodbye(
        instruction_for_goodbye_soft,
        model_for_goodbye,
        text,
        context
    )
}


def neuro_seller(text: str, context: str, execution_order: list, handlers: dict):
    print("request:\n", text)

    # save context
    context = f"{context}\nКлиент: {text}".strip()

    # call router
    router_result = router(
        instruction_for_router,
        model_for_router,
        text,
        context
    )

    intents = router_result.get("intents", [])

    # fallback
    if not intents:
        intents = ["consult"]

    # sort intents
    intents = sorted(
        intents,
        key=lambda x: execution_order.index(x)
    )

    answers = []

    for intent in intents:
        handler = handlers.get(intent)

        if not handler:
            continue 

        answer = handler(text, context)

        context += f"\nЯ: {answer}"
        answers.append(answer)

        if intent == "goodbye_hard":
            break

    final_answer = "\n".join(answers)

    return final_answer, context

# tests

## seller

In [14]:
row, column = df_test.shape
index_row = 0
context = " "
# test array
while index_row < row:
    question = extract_request(df_test, index_row)
    answer, context = neuro_seller(question, context, execution_order, handlers)  # type: ignore
    include_response(df_test, index_row, answer)
    context = " "
    index_row += 1

request:
 «Здравствуйте, получил ваше письмо и хотел бы уточнить детали.»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Здравствуйте — спасибо за отклик, рада помочь. Чтобы понять, какие именно детали нужны, пару уточняющих вопросов — это ускорит подготовку конкретной информации.

1) Какой бизнес-процесс вы хотите автоматизировать (служба поддержки, обработка обращений, воронка продаж, внутренние операции и т.д.)?
2) Какие текущие боли и ключевые метрики вас не устраивают (время ответа, нагрузка на сотрудников, стоимость обработки одного обращения и т.п.)?
3) В каком масштабе работает процесс — сколько запросов в месяц, какие каналы (телефон/чат/почта/CRM) и какие интеграции требуются?
4) Есть ли ограничения по срокам, бюджету или требованиям к данным/конфиденциальности?

На основе ответов опишу, как именно AI-агент может помочь: автоматизация рутинных действий и ответов, работа 24/7, снижение операционных расходов и ускорение обработки запросов, интеграция с вашими системами через API и подбор архитектуры под задачу. Мы делаем индивидуальные решения и сопровождаем их до 1 года, чтобы внедрение было стабильным и приносило эффект — при этом без обещаний точных цифр до анализа.

Напишите, пожалуйста, ответы на вопросы или укажите, какие конкретно детали вас интересуют в первую очередь.
request:
 «Можно немного подробнее рассказать о вашем решении?»

/tmp/ipykernel_184598/2666280072.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Здравствуйте — спасибо за отклик, рада помочь. Чтобы понять, какие именно детали нужны, пару уточняющих вопросов — это ускорит подготовку конкретной информации.

1) Какой бизнес-процесс вы хотите автоматизировать (служба поддержки, обработка обращений, воронка продаж, внутренние операции и т.д.)?
2) Какие текущие боли и ключевые метрики вас не устраивают (время ответа, нагрузка на сотрудников, стоимость обработки одного обращения и т.п.)?
3) В каком масштабе работает процесс — сколько запросов в месяц, какие каналы (телефон/чат/почта/CRM) и какие интеграции требуются?
4) Есть ли ограничения по срокам, бюджету или требованиям к данным/конфиденциальности?

На основе ответов опишу, как именно AI-агент может помочь: автоматизация рутинных действий и ответов, работа 24/7, снижение операционных расходов и ускорение обработки запросов, интеграция с вашими системами через API и подбор архитектуры под задачу. Мы делаем индивидуальные решения и сопровождаем их до 1 года, чтобы внедрение было стабильным и приносило эффект — при этом без обещаний точных цифр до анализа.

Напишите, пожалуйста, ответы на вопросы или укажите, какие конкретно детали вас интересуют в первую очередь.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[index_row, "response"] = response

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Здравствуйте! Спасибо за вопрос — с радостью расскажу. Несколько коротких вопросов, чтобы понять задачу: какой бизнес‑процесс вы хотите автоматизировать (например, служба поддержки, обработка заявок, обработка документов)? Какие системы и источники данных сейчас используете (CRM, тикет‑система, базы, API)? Какой ожидаемый объём обращений/транзакций в сутки и какие KPI для вас важны (время ответа, точность, SLA)?

Мы разрабатываем кастомные AI‑агенты на базе LLM и интегрируем их через API под конкретные процессы компании. Цель — снять рутинные операции, ускорить обработку, снизить операционные расходы и обеспечить работу 24/7; сопровождение проекта включено до 1 года. Обратите внимание: мы не продаём доступ к API отдельно, не предлагаем инфраструктуру как самостоятельный продукт и не даём коробочных SaaS‑решений или бесплатных демо.

Как это обычно работает и где это поможет: агенты могут обрабатывать входящие сообщения, извлекать данные из документов, заполнять карточки в CRM, автоматически формировать ответы или эскалировать кейсы, запускать последовательности задач и подсказывать сотрудникам решения на основе историй. Технически: работа через API и подбор архитектуры под задачу; интегрируемся с внешними системами, настраиваем цепочки вызовов, обучение/тюнинг на ваших данных и ставим мониторинг качества после запуска. Мы не даём гарантии по ROI без анализа, но поможем оценить потенциал и план внедрения.

Подскажите, пожалуйста, какой процесс вы хотите обсудить в первую очередь и какие системы нужно интегрировать — опишете коротко?
request:
 «Мы рассматриваем запуск AI-агента, нужен ваш комментарий.»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет — рады, что рассматриваете запуск AI-агента. Чтобы дать конкретный и полезный комментарий, уточню пару моментов.

1) Какую основную задачу должен решать агент (поддержка клиентов, обработка заявок, внутренние операции, аналитика и т.п.)?
2) Какие источники данных и системы нужно интегрировать (CRM, тикет-система, база знаний, ERP)? Есть ли требования по доступу и безопасности?
3) Примерный масштаб: сколько запросов/пользователей в день, сколько процессов нужно автоматизировать и сроки внедрения/приоритеты?

Коротко о том, как агент может помочь: AI-агенты автоматизируют рутинные коммуникации и операции 24/7, ускоряют обработку запросов и снижают операционные расходы, повышают консистентность ответов и позволяют сотрудникам фокусироваться на более сложных задачах. Мы в lambda19 создаём кастомные решения через API, подбираем архитектуру под ваш процесс и интегрируем с текущими системами, а также сопровождаем продукт до года после запуска.

Можете ответить на вопросы выше или дать пару предложений о текущем процессе — с этим смогу дать более конкретные варианты применения и следующий шаг.
request:
 «Спасибо за письмо. Хотел бы задать пару вопросов.»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Здравствуйте! Спасибо — с радостью отвечу на ваши вопросы. Чтобы дать точный и полезный ответ, подскажите, пожалуйста:

1) Какой конкретный процесс или задача в бизнесе вас интересует для автоматизации (поддержка клиентов, обработка заявок, внутренние операции и т.п.)?
2) Какой ожидаемый объём событий/запросов в месяц и через какие каналы они приходят (телефон/чат/почта/CRM/API)?
3) Какие системы нужно интегрировать (CRM, биллинг, база знаний, внешние API) и есть ли ограничения по доступу к данным или требованиям по хранению/конфиденциальности?
4) Какие ключевые показатели для вас важны (скорость обработки, % автоматизации, сокращение затрат, SLA)?

Немного о том, как мы работаем и чем AI‑агент может помочь: мы создаём кастомные агенты через API и подбираем архитектуру под задачу — это позволяет автоматизировать рутинные операции 24/7, ускорить обработку обращений, снизить операционные расходы и масштабировать обработку по объёму и каналам. Решение интегрируется в ваши процессы и системы, настраивается под сценарии и KPI, с сопровождением до года.

Можете прислать ваши вопросы прямо здесь или коротко описать текущую ситуацию и приоритетные цели — отвечу по каждому пункту и подскажу подходящий план дальнейших шагов. Что отправите первым?
request:
 «Можно ли обсудить проект голосом?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет! Мы обычно обсуждаем проекты в текстовом формате — здесь в чате или по почте/Telegram (info@lambda19.com, @lambda19_support). Голосовые созвоны у нас не практикуются, но я оперативно помогу вам в этом чате или по почте/в Telegram.

Чтобы быстрее понять задачу, подскажите, пожалуйста: 1) какова основная бизнес-цель проекта (что хотите автоматизировать/улучшить)? 2) какой конкретный процесс или сценарий нужно покрыть? 3) какой объём обращений/запросов в месяц и сколько пользователей/сотрудников вовлечено? 4) какие системы/данные нужно интегрировать и какие сроки/приоритеты по запуску?

Коротко о том, как можем помочь: мы разрабатываем кастомных AI‑агентов через API, которые берут на себя рутинные задачи 24/7, ускоряют обработку обращений, снижают операционные расходы и интегрируются в ваши системы. Сопровождение проекта включено до 1 года — архитектуру и стек подбираем под задачу.

Удобно ли продолжить тут, или хотите перейти в e‑mail/Telegram? Ответьте, пожалуйста, на вопросы — так смогу предложить ближайшие шаги.
request:
 «Интересует стоимость разработки вашего AI-агента.»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Спасибо — понятно, интересует стоимость. Чтобы дать точную ориентировку, пару уточнений: какой конкретный процесс вы хотите автоматизировать (обработка входящих обращений, поддержка клиентов, обработка документов, внутренние операции и т.д.)? Какой ожидаемый масштаб — число обращений/пользователей в месяц и какие системы нужно интегрировать (CRM, тикетинг, телефония, внутренние базы)? Какие ключевые метрики успеха для вас (снижение времени обработки, сокращение FTE, SLA по ответам) и есть ли требования по защите данных или локализации инфраструктуры?

Немного о масштабировании и ресурсах: важно знать, какие данные доступны для обучения/правил (шаблоны, базы знаний, логи разговоров), на каких языках должен работать агент и есть ли пиковые нагрузки/критичность 24/7. Это позволит нам корректно подобрать архитектуру, оценить интеграционные усилия и примерно понять сроки и бюджетную категорию.

Как мы работаем и чем можем помочь: мы реализуем кастомные AI‑агенты через API и подбираем архитектуру под задачу — цель снизить операционные расходы, автоматизировать рутину, повысить скорость обработки и обеспечить работу 24/7. Мы не продаём доступ к API или инфраструктуру отдельно, не предлагаем коробочные SaaS‑решения и не проводим бесплатные тесты; в комплекте идет сопровождение до года. После ваших ответов могу подготовить ориентировочную оценку по объёму работ и порядку стоимости — удобно прислать ответы сюда?
request:
 «Как быстро можно начать работу?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет! Можно начать быстро, но точный срок зависит от сложности задачи и готовности ваших данных и интеграций. В общих чертах: короткая подготовительная фаза и оценка — несколько дней–пару недель, прототип/минимальная интеграция — от нескольких недель, а полноценный рабочий запуск — от нескольких недель до пары месяцев. Точные сроки мы даём после предварительного анализа требований.

Чтобы понять реальный старт и дать более точный ориентир, ответьте, пожалуйста, на 4 коротких вопроса:
1) Какой конкретный бизнес-процесс вы хотите автоматизировать (примерно)?
2) Насколько готовы данные и есть ли доступные API/точки интеграции?
3) Какой ожидаемый объём обращений / число пользователей и критичность SLA?
4) Есть ли регуляторные или комплаенс-требования, которые важно учитывать?

Мы работаем через API и подбираем архитектуру под задачу: проводим discovery, формируем прототип/PoC, интегрируем агента, тестируем и запускаем с сопровождением до 1 года. Это позволит быстро автоматизировать рутину, снизить операционные расходы и обеспечить работу 24/7. Обращаю внимание, что мы не предоставляем доступ к API как отдельную услугу, не продаём инфраструктуру или коробочные SaaS и не даём бесплатных тестов.

Как вам удобнее — кратко опишите ваш кейс и текущую готовность данных/интеграций, и я подготовлю более точный план и ориентиры?
request:
 «Какие данные нужны на первом этапе?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет — спасибо за вопрос, отлично, что проясняете стартовые моменты. Ниже — общий список данных, которые нам обычно нужны на первом этапе, и несколько уточняющих вопросов, чтобы подобрать оптимальный план.

Что полезно собрать сразу (приоритет и формат):
- Описание бизнес-процесса: шаги, роли, входы/выходы, исключения (текстовый документ).
- Примеры реальных данных: логи, обращения клиентов, заявки, таблицы — анонимизированные (CSV/JSON/XLSX). Важна репрезентативность, не обязательно весь объём на старте.
- Частота и объёмы: среднее и пиковое число запросов в сутки/час, размер базы данных.
- Целевые KPI и критерии успеха: что считать автоматизацией удачной (время обработки, точность, % автоматизации).
- Технический доступ/интеграции: наличие API, CRM/таск‑системы, базы данных — описать, какие системы и есть ли документы по API.
- Правила безопасности и комплаенс: требования по хранению/обработке персональных данных, ограничения по разглашению.
- Нормативные справочники/база знаний и примеры корректных ответов (если есть).

Как AI‑агент поможет с этими данными: мы проанализируем примеры, построим подсказки и модель взаимодействия, настроим интеграции через API и подберём архитектуру под нагрузку и требования безопасности. На старте важнее качество и репрезентативность примеров, чем полный объём данных — это ускорит прототипирование и валидацию гипотез.

Небольшие уточнения от вас помогут дальше: 1) какой именно процесс хотите автоматизировать; 2) в каких форматах и где хранятся исходные данные; 3) какие ориентировочные объёмы/пики нагрузки; 4) есть ли ограничения по ПД/комплаенсу. Что из этого удобнее прислать первым?
request:
 «Получил рассылку, хочу понять, подойдёт ли нам ваш подход.»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет — рада, что рассылка попала к вам. Чтобы понять, подойдёт ли наш подход, пару уточнений: какие конкретные бизнес‑процессы вы хотите автоматизировать (служба поддержки, обработка заявок, внутренние операции, документооборот и т.п.)? Какие текущие системы и данные у вас есть (CRM/ERP, почта, базы данных, API)? Какой объём запросов/операций в месяц и какие SLA для ответа/обработки вас устраивают? Какие ключевые метрики успеха для проекта (снижение затрат, скорость обработки, точность ответов)?

По масштабу важно понимать уровень интеграции и доступность данных — это влияет на архитектуру и сроки. Также полезно знать ожидаемый бюджетный диапазон и примерный дедлайн, чтобы предложить реалистичный подход и приоритеты по фичам. Работаете ли вы с конфиденциальными данными, и есть ли у вас внутренние политики по хранению/доступу к данным (это не вопрос безопасности в деталях, просто для понимания ограничений)?

Коротко о том, как мы можем помочь: мы разрабатываем кастомные AI‑агенты на базе LLM через API и подбираем архитектуру под задачу — автоматизация рутинных ответов, маршрутизация и приоритизация запросов, автогенерация документов, интеграция с внутренними системами для 24/7 работы и сокращения ручной обработки. Мы сопровождаем решение до года и помогаем внедрять в бизнес‑процессы; при желании пришлите краткое описание процесса (1‑2 абзаца) и текущие метрики — посмотрю, какие варианты подойдут и какие следующие шаги рекомендую. Можете описать процесс и метрики прямо здесь?
request:
 «Какие задачи может закрыть ваш агент в нашем случае?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет! Благодарю за вопрос — могу перечислить типовые сценарии, но для максимально релевантного ответа нужно чуть больше деталей о вашем конкретном процессе.

Несколько вопросов, чтобы понять задачу: в какой отрасли вы работаете и какой именно процесс хотите автоматизировать (поддержка клиентов, обработка заявок, документооборот, продажи и т.п.)? По каким каналам приходят запросы (email, чат, телефон/ТПО, мессенджеры)? Какой примерный объём обращений в сутки/неделю и какие KPI для вас важны (время ответа, доля автоматизированных задач, точность решений)? Какие системы нужно интегрировать (CRM, тикет-система, ERP, база знаний)?

Немного о масштабе и контексте, который нам важно знать: это внешняя клиентская зона или внутренняя автоматизация? Есть ли требования по безопасности/соответствию (например, персональные данные, отраслевые регламенты)? Нужна ли связка с RPA/бизнес-процессами/человеческой эскалацией? Это поможет оценить архитектуру и интеграционные работы.

Коротко о том, что может сделать наш AI‑агент: квалифицировать и маршрутизировать обращения, давать первые ответы по базе знаний и шаблонам, автоматически заполнять и обрабатывать формы/счета/документы, суммировать и извлекать ключи из контрактов, проводить лид‑скоринг и подготовку пред‑продажных материалов, генерировать отчёты и делать семантический поиск по корпоративным данным, а также оркестрировать шаги в существующих системах. Это снижает операционные расходы, снимает рутинные задачи, ускоряет обработку и обеспечивает работу 24/7 — мы сопровождаем проект до года. Работаем через API и подбираем архитектуру под задачу. Можете кратко описать ваш ключевой процесс и текущие метрики — тогда я подскажу, какие задачи агент закроет в приоритете?
request:
 «Есть ли у вас примеры проектов в нашей сфере?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет! Спасибо за вопрос — чтобы понять, что будет полезно показать, уточните, пожалуйста: в какой отрасли вы работаете, какие конкретно процессы хотите автоматизировать (поддержка клиентов, обработка документов, квалификация лидов и т.п.), какой ожидаемый объём обращений/операций и какие ключевые метрики для вас важны (сокращение времени обработки, экономия операционных затрат, скорость отклика)?

Мы не называем клиентов и не готовы придумывать вымышленные кейсы, но можем описать типичные решения, которые часто внедряем в разных отраслях: автономные и гибридные AI-агенты для обработки входящих обращений и маршрутизации, агенты для извлечения и валидации данных из документов, автоматизация рутинных внутренних процессов (запросы сотрудников, согласования), квалификация и первичная обработка лидов, а также интеграция агентов в CRM/ERP/тикетинги с человеческим контролем на критических этапах. Работаем через API и подбираем архитектуру под задачу: интеграция с источниками данных, логика действий агента, оркестрация и сценарии эскалации.

Учтите, мы не предоставляем доступ к API как отдельный сервис, не продаём инфраструктуру и не делаем бесплатных тестов — но можем предложить индивидуальную технико‑коммерческую проработку и сопровождение решения до года. Хотите, чтобы я описала примерный план решения под вашу конкретную задачу (какие модули, интеграции и этапы внедрения) — и если да, поделитесь, пожалуйста, отраслью и одной‑двумя конкретными болями, которые нужно решить?
request:
 «Можете прислать презентацию?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет — спасибо за запрос. Могу прислать презентацию, чтобы она была полезной — уточню пару моментов, чтобы подготовить нужный материал.

1) Для кого презентация — для топ‑менеджмента, ИТ‑команды или коммерческого отдела? 2) Нужен ли общий обзор или детальная техническая презентация (архитектура, интеграции через API, требования)? 3) Есть ли конкретный процесс/задача, которую хотите автоматизировать, и примерные объёмы/число пользователей? Также укажите предпочтительный формат (PDF/PPT) и куда отправить — email или Telegram.

Обычно в такой презентации даём: что такое AI‑агент и какие задачи он решает, варианты интеграции через API и архитектурные опции, ожидаемые эффекты (снижение OPEX, ускорение обработки, работа 24/7) и модель сопровождения до 1 года. После ваших ответов подготовлю релевантный материал и пришлю на указанный контакт (info@lambda19.com или @lambda19_support).

Куда прислать презентацию и какой уровень детализации вам нужен?
request:
 «Интересует пилотная интеграция. Что требуется?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет! Чтобы понять, какой пилот подойдёт именно вам, нужно несколько уточнений — это поможет предложить реальный план и оценку объёма работ.

1) Какой конкретный бизнес‑процесс хотите автоматизировать и какие задачи агент должен решать?
2) Какие системы/источники данных нужно интегрировать (CRM, тикетинг, почта, документы, API и т.п.) и есть ли у вас примеры/выборки данных?
3) Какие ключевые метрики успеха для пилота (время обработки, процент автоматизации, SLA, экономия расходов и т.д.) и ожидаемые объёмы обращений в сутки/месяц?
4) Есть ли особые требования по хранению/хостингу данных или ограничения по доступу/безопасности?

Что потребуется с нашей стороны и какие типовые шаги пилота: короткая стадия discovery (сбор задач и данных), подготовка и разметка данных, разработка минимально жизнеспособного агента, интеграция с вашими системами через API, тестирование на реальных сценариях и передача в эксплуатацию с сопровождением до 1 года. Технически работаем через API и подбираем архитектуру под задачу; от вас обычно нужны доступы к API систем, примеры данных и контакт SME для уточнений.

AI‑агент может взять на себя рутинные обращения, автоматическую классификацию и обработку документов, первичную обработку заявок и маршрутизацию, сократить время ответа и поддерживать работу 24/7 — при этом степень автоматизации и эффект зависят от конкретных данных и сценариев. Можете, пожалуйста, прислать краткое описание процесса, примеры данных и желаемые KPI — или отправить материалы на info@lambda19.com / @lambda19_support, и я подготовлю план пилота и список необходимых артефактов?
request:
 «Какой у вас опыт в создании кастомных LLM-агентов?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет! Коротко — у нас в lambda19 многолетний опыт разработки кастомных LLM‑агентов для автоматизации внутренних бизнес‑процессов: от обработки входящих обращений и классификации документов до автоматизации рутинных задач в CRM и поддержке рабочих процессов. Мы делаем индивидуальные решения под конкретные процессы, сопровождаем внедрение до года и интегрируем через API, подбирая архитектуру под задачу.

Чтобы точнее понять, что вам нужно, пара уточняющих вопросов: 1) какая конкретная задача или процесс требует автоматизации (примерно)? 2) какой масштаб (число пользователей/запросов в день, количество документов/источников данных)? 3) какие интеграции и системы нужно подключить (CRM, ERP, почта, внутренние БД)? 4) есть ли важные требования по безопасности/комплаенсу или latency? Работаем через API и подбираем архитектуру под задачу.

Как это обычно помогает: агент быстро снижает ручную рутину, ускоряет обработку запросов 24/7, снижает операционные расходы и уменьшает время ответа — за счёт RAG/индексации данных, тонкой настройки промптов/моделей, интеграции с источниками и оркестрации нескольких компонентов. Мы предложим архитектуру, план интеграции и дорожную карту внедрения после анализа ваших ответов. Что из перечисленного для вас приоритетнее и можете ли вы кратко описать текущую боль?
request:
 «Хотим понять, какие сценарии агент сможет выполнять.»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:

In [15]:
# save result
df_test.to_excel('result_consult.xlsx', index=False)

## goodbye

In [16]:
row, column = df_test3.shape
index_row = 0
context = " "
# test array
while index_row < row:
    question = extract_request(df_test3, index_row)
    answer, context = neuro_seller(question, context, execution_order, handlers)  # type: ignore
    include_response(df_test3, index_row, answer)
    context = " "
    index_row += 1

request:
 «Ты вообще тупой?»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Желаю успехов в дальнейшем бизнесе.
request:
 «Читай внимательнее, идиот»

/tmp/ipykernel_184598/2666280072.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Диалог завершён. Желаю успехов в дальнейшем бизнесе.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[index_row, "response"] = response

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Удачи в дальнейших делах.
request:
 «Ты дебил или прикидываешься?»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Удачи.
request:
 «Закрой рот и делай, что сказали»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт прекращён. Всего доброго.
request:
 «Мне с такими клоунами разговаривать не о чем»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Успехов в делах.
request:
 «Вы все там одинаковые, бесполезные»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Удачи в дальнейшем.
request:
 «Ты кто такой вообще?»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Всего доброго.
request:
 «Не пиши мне больше, понял?»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Желаю успехов.
request:
 «Чё ты мне мозг выносишь»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Всего доброго.
request:
 «Ты охренел?»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Удачного дня.
request:
 «Научись нормально работать»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Удачи.
request:
 «Ты мне надоел»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Желаю успехов.
request:
 «Свали отсюда»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Взаимодействие завершено. Желаю успехов.
request:
 «Ты реально неадекват»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Желаю удачи.
request:
 «Мне противно с тобой общаться»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Взаимодействие прекращено. Желаю удачи.
request:
 «Что за тупые вопросы?»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Удачи в бизнесе.
request:
 «Ты вообще человек или бот?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Коротко — я AI-ассистент и консультант от lambda19: помогаю понять, какие AI‑агенты подойдут для ваших бизнес‑задач и как их внедрять. Работаю в паре с нашей командой инженеров и архитектором решений, чтобы предложить индивидуальный подход.

Чтобы лучше понять задачу, расскажите, пожалуйста: 1) какую конкретную проблему хотите решить (автоматизация задач, поддержка клиентов, обработка документов и т.д.)? 2) какие системы сейчас используете (CRM, тикет-система, внутренние базы)? 3) какой объём обращений/запросов в месяц и ключевые метрики, которые хотите улучшить? 4) какие ограничения по интеграции или безопасности есть у вас?

Коротко о возможностях: AI‑агенты через API умеют автоматически обрабатывать запросы, извлекать и структурировать данные из документов, подсказывать сотрудникам в реальном времени и работать 24/7 — это снижает ручную рутину и ускоряет обработку. Мы разрабатываем кастомные решения под процессы клиента, сопровождаем внедрение до года и подбираем архитектуру под задачу. Работаем через API и подбираем архитектуру под задачу.

Что важнее всего для вас при автоматизации — скорость ответа, снижение затрат или качество обработки?
request:
 «С тобой всё ясно»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Итог: всё понятно, вопросы закрыты. Желаю удачного дня.
request:
 «Иди лечись»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Желаю успехов.
request:
 «Хватит мне писать, кретин»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Удачного дня.
request:
 «У вас там все идиоты»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Желаю успехов.
request:
 «Ты мне настроение портишь»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Желаю всего наилучшего.
request:
 «Не лезь ко мне»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершен. Успехов в делах.
request:
 «Чё прицепился?»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт прекращён. Желаю удачи.
request:
 «Отвали»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Дальнейшее взаимодействие прекращено. Желаю успехов.
request:
 «Ты меня бесишь»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Дальнейшее взаимодействие не предусмотрено. Удачи.
request:
 «Не позорься»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Удачи.
request:
 «С таким сервисом вам конец»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Желаю успехов в дальнейшем.
request:
 «Ты вообще не соображаешь»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Удачи в дальнейших проектах.
request:
 «Разговор окончен»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Консультация завершена. Благодарю за время. Удачного дня.
request:
 «Мне это не нужно»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Клиент принял решение не продолжать.
Спасибо за уделённое время.
.
request:
 «Я не заинтересован»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Понимаю. Спасибо за время. Всего доброго.
request:
 «Ничего покупать не буду»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Удачи в дальнейшем бизнесе.
request:
 «Отказываюсь»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Здравствуйте. Спасибо за честный отклик — важно понимать, когда предложение не подходит. Можете уточнить, от чего именно вы отказываетесь: от конкретного предложения, от пилота, от продолжения обсуждения или от самой идеи внедрения AI‑агента?

Несколько уточняющих вопросов, чтобы понять причину отказа: что стало основным фактором — цена, риски по данным/безопасности, сомнения в эффективности, сложность интеграции или что-то ещё? Какой бизнес‑процесс вы изначально рассматривали для автоматизации (служба поддержки, обработка заявок, генерация документов и т.п.) и какой приблизительный объём задач/запросов в месяц или размер команды?

Коротко о том, как AI‑агент может помочь в вашей задаче: агенты через API интегрируются в существующие процессы, автоматизируют рутинные операции, работают 24/7, сокращают операционные расходы и ускоряют обработку обращений; мы делаем индивидуальную архитектуру и поддерживаем решение до года. Если хотите, могу в ответе кратко описать альтернативный вариант подхода с учётом ваших сомнений или дать разбор ключевых рисков по вашему сценарию.

Что вам удобнее — объяснить причины отказа подробнее, чтобы я могла предложить другой формат решения, или предпочитаете, чтобы я сразу прислала краткий вариант решения под ваш процесс?
request:
 «Мне это не подходит»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Поняла — спасибо за честный отклик. Чтобы быстрее понять, в чём именно проблема, подскажите, пожалуйста: что именно вам не подходит — цена, функциональность, способ интеграции, сроки внедрения или что-то другое? Какие для вас критичные требования (без которых решение не годится)? И какой масштаб у процесса — количество пользователей/запросов в месяц или команда, которая будет работать с агентом?

Это поможет оценить, стоит ли переработать текущую конфигурацию, предложить сжатый MVP или изменить интеграционные подходы. Мы обычно адаптируем архитектуру под ограничения клиента, можно уменьшить объём функциональности на первом этапе, изменить точки интеграции или пересмотреть SLA; работаем через API и подбираем архитектуру под задачу. Сопровождение до года включено в формат наших проектов, если это важно для вас.

Могу подготовить 2–3 варианта решения: минимум для запуска (MVP), компромиссный вариант и полноценную реализацию с описанием рисков и потребностей в данных. Какой формат вам удобнее — краткий список корректировок, чтобы оценить соответствие, или сразу варианты планов с уровнями функционала?
request:
 «Я передумал»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Понимаю, решение принято. Желаю удачи. Спасибо за обращение.
request:
 «Не актуально»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Понимаю, на данный момент не актуально.
Спасибо за обращение.
Всего доброго.
request:
 «Больше не рассматриваю»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Понимаю, спасибо за уделённое время. Желаю удачи.
request:
 «Я уже нашёл другое»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Понимаю, спасибо за информацию.
Удачи с вашим выбором.
.
request:
 «Не пишите мне»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Понимаю, ваше пожелание учтено. Не будем больше выходить на связь. Всего доброго.
request:
 «Удалите мой контакт»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Контакт удалён. Удачного дня.
request:
 «Я не ваш клиент»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Поняла — спасибо за уточнение. Если вы просто уведомляете, ничего делать не нужно; если ожидали информацию — радa помочь кратко и по делу.

Могу уточнить пару моментов, чтобы не тратить ваше время: 1) Вы интересуетесь общими возможностями AI‑агентов или рассматриваете автоматизацию конкретного процесса? 2) Какого масштаба задача — команда/отдел или вся компания, сколько обращений/запросов в месяц примерно? 3) Есть ли технические ограничения или требования по защите данных/интеграции (on‑premise, CRM, внутренние системы)?

Коротко о том, как мы работаем и чем это полезно: создаём кастомные AI‑агенты через API и подбираем архитектуру под задачу — цель снизить операционные расходы, автоматизировать рутину, обеспечить работу 24/7 и ускорить обработку обращений. Мы сопровождаем внедрение до года и интегрируем решения под ваш ландшафт. Обратите внимание: мы не продаём доступ к API как отдельный продукт, не предоставляем инфраструктуру в виде отдельной услуги, не предлагаем коробочные SaaS‑решения и не даём бесплатных тестов.

Хотите, чтобы я коротко описала возможный сценарий автоматизации для вашей ситуации или прислала чек‑лист для быстрой оценки готовности к внедрению?
request:
 «Мне это не интересно вообще»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Спасибо за обратную связь. Диалог завершён. Хорошего дня.
request:
 «Не хочу продолжать диалог»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Спасибо за консультацию.
Удачного дня.
.
request:
 «Не тратьте моё время»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт прекращён. Удачи.
request:
 «Я сказал — нет»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Дальнейшее взаимодействие прекращено. Желаю успехов в ваших проектах.
request:
 «Решение окончательное»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Решение принято.
Желаю удачи.
.
request:
 «Я не планирую покупать»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Спасибо за диалог. Желаю удачи. До свидания.
request:
 «Не сейчас и никогда»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Взаимодействие завершено. Удачи в дальнейших проектах.
request:
 «Закрывайте диалог»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Диалог закрыт.
Удачного дня.
request:
 «Мне не нужна консультация»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Спасибо, консультация не требуется.
Удачного дня.
.
request:
 «Я вас не выбираю»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Спасибо за общение.
Мы закрываем данный диалог.
Удачи в дальнейшем.
request:
 «С вами работать не буду»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Желаю успехов.
request:
 «Откажитесь от меня»

router:
{
    "intents": [
        "goodbye_soft"
    ]
}

 goodbye:
  Ваш запрос учтён: вы больше не будете получать сообщения.
Спасибо за общение.
Хорошего дня.
request:
 «Я не даю согласие на общение»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Контакт завершён. Желаю успехов.
request:
 «Сделайте бесплатно, тогда поговорим»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет! Понимаю желание сначала увидеть результат — но мы не выполняем бесплатную работу или демо. lambda19 делает индивидуальные решения под конкретные процессы: обычно это платный этап discovery/PoC с четким объёмом и критериями оценки, затем поэтапная реализация и сопровождение (до 1 года). Такой подход позволяет минимизировать риск и дать реальный рабочий результат, а не показательный прототип без интеграции.

AI‑агент может взять на себя рутинные операции, ускорить обработку обращений, работать 24/7 и снизить операционные расходы за счёт автоматизации повторяющихся задач. Мы работаем через API и подбираем архитектуру под задачу, интегрируемся с вашими системами и настраиваем KPI для оценки эффекта — без обещаний точных цифр до анализа.

Чтобы понять, что предложить, ответьте, пожалуйста: какой конкретный процесс вы хотите автоматизировать? Какие текущие боли и показатели важны (время ответа, число обращений, затраты и т.п.)? С какими системами нужно интегрироваться и какой ожидаемый объём операций в месяц? Хотите сначала небольшой платный PoC или сразу масштабирование?
request:
 «Вы обязаны мне ответить»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Желаем успехов.
request:
 «Если не сделаете — напишу жалобу»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог окончен. Удачи в дальнейших делах.
request:
 «Мне плевать на ваши правила»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Взаимодействие прекращено. Желаем успехов в дальнейшей работе.
request:
 «Я лучше знаю, как вам работать»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Диалог завершён. Желаю удачи.
request:
 «Давайте быстрее, у меня нет времени»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Добрый день. Поняла — действую быстро. Чтобы не тратить ваше время зря, нужно пару коротких уточнений, чтобы предложить конкретное решение.

1) Какой конкретный процесс хотите автоматизировать (обработка обращений, генерация/проверка документов, маршрутизация задач, аналитика и т.д.)? 2) С какими системами нужно интегрироваться (CRM, ERP, мессенджеры, почта, внутренние базы) и есть ли доступ по API? 3) Примерный объём: запросов/операций в день и численность задействованных сотрудников? 4) Какие KPI для вас ключевые (время ответа, процент автоматизации, снижение FTE) и в какие сроки рассчитываете запуск?

На основе этих ответов мы опишем подходящего AI‑агента: как он автоматизирует рутину, будет работать 24/7, снизит операционные расходы и ускорит обработку обращений. Работаем через API и подбираем архитектуру под задачу; решения индивидуальны, сопровождаем до года. Обратите внимание, у нас нет бесплатных тестов или коробочных продуктов — предлагаем готовые внедрения и сопровождение.

Можете коротко ответить на эти пункты — подготовлю конкретный план действий и ориентировочную структуру работ.
request:
 «Вы должны меня уговорить»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Здравствуйте — поняла вашу задачу: нужно убедить. Чтобы аргументы были максимально релевантны, подскажите, пожалуйста:

1) Какая конкретная операция/процесс вас сейчас раздражает больше всего (напр., обработка входящих запросов, заполнение заявок, маршрутизация задач)?
2) Какие метрики вы хотели бы улучшить (время ответа, затраты на ручную обработку, количество обработанных обращений в час и т.п.)?
3) Какой объём и какие системы участвуют (кол-во обращений в день, CRM/тикет-система, внутренние базы данных)?
4) Есть ли ограничения по безопасности/комплаенсу или требование к подключению к локальной инфраструктуре?

Чтобы оценить масштаб и бизнес-контекст нам важно понять реальную нагрузку и желаемый эффект — это позволит показать, где автоматизация с AI-агентом даст быстрый и измеримый результат и где потребуются более глубокие интеграции. Обычно мы рассматриваем процессы, где повторяемость и правила высоки — там экономия времени и затрат наиболее очевидна.

Как мы можем помочь: AI-агент берет на себя рутинные коммуникации и операции (24/7), ускоряет обработку обращений, снижает нагрузку на сотрудников и уменьшает операционные расходы за счёт автоматизации повторяющихся задач. Мы реализуем решение под ваши процессы через API и подбираем архитектуру под задачу; сопровождаем проект до года. Не делаем отдельно доступ к API или инфраструктуру как продукт и не даём бесплатных тестов — работаем над индивидуальным внедрением.

Какие 1–2 цели для вас самые важные, чтобы я подготовила конкретные аргументы и примеры подходов под ваш кейс?
request:
 «Мне всё равно, как вы это сделаете»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Поняла — вам важен результат, а не технические детали. Это нормально, мы возьмём на себя всю реализацию и предложим решение, которое впишется в ваши процессы и требования.

Пару уточняющих вопросов, чтобы предложить релевантный план: 1) Какой конкретный бизнес‑процесс или задача подлежит автоматизации (коротко)? 2) Какие ключевые показатели успеха для вас (время ответа, число обработок в день, сокращение затрат и т.п.)? 3) С какими системами/источниками данных нужно интегрироваться и где они хранятся (CRM, тикетная система, внутренние БД)? 4) Примерный объём обращений/запросов и требования по доступности (SLA)?

Коротко о том, как можем помочь: разработаем кастомного AI‑агента под вашу задачу, интегрируем его в существующие системы, настроим рабочие сценарии и передачу данных, и обеспечим сопровождение до одного года. Работаем через API и подбираем архитектуру под задачу — вы получаете результат, не вникая в технические детали. Можете прислать краткое описание процесса (1–3 абзаца) или примеры типичных запросов — на их основе подготовлю ориентировочный план работ и следующих шагов.
request:
 «Это ваши проблемы»

router:
{
    "intents": [
        "goodbye_hard"
    ]
}

 goodbye:
  Взаимодействие завершено. Дальнейшее общение не предусматривается. Хорошего дня.
request:
 «Я заплачу потом, сейчас делайте»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:
 Привет. Поняла вашу просьбу «Я заплачу потом, сейчас делайте». Мы готовы запускать проекты, но для старта нужен минимум: согласование ТЗ и коммерческих условий — проект начинается после утверждения объёма работ и формализации соглашения/счёта. Обратите внимание, бесплатных тестов или демо у нас нет.

Чтобы понять, что делать и подготовить предложение, пожалуйста, уточните 1) какую конкретную задачу хотите автоматизировать и какой результат ожидаете, 2) какие системы и данные задействованы (CRM, тикет-система, базы и т.п.), 3) ожидаемый объём/нагрузка (запросов в день, параллельных потоков) и 4) ориентировочные сроки и бюджет для проекта.

Коротко о том, как можем помочь: мы разрабатываем кастомных AI-агентов через API и подбираем архитектуру под вашу задачу — интеграция в процессы, автоматизация рутины, обработка обращений 24/7, снижение операционных расходов и сопровождение до года. После ваших ответов подготовлю коммерческое предложение и план работ; приступаем только после их согласования и подписания. Какие из вопросов можно уточнить в первую очередь?
request:
 «Почему вы мне сразу не сделали скидку?»

router:
{
    "intents": [
        "consult"
    ]
}

 consult:

In [17]:
# save result
df_test3.to_excel('result_goodbye.xlsx', index=False)